version: "3"

services:
  postgresql:
    image: postgres
    restart: always
    container_name: guestbook-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: guestbook
      POSTGRES_USER: guestbook
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
